title: GPS on wheels

#baseurl: /Motorization
#url: "http://gps-robotic.github.io/Motorization"

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# White-listed plugins
gems:
  - jekyll-sitemap
